<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBqfzhy8\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBqfzhy8/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBqfzhy8.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBqfzhy8\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBqfzhy8\appProdProjectContainer([
    'container.build_hash' => 'Bqfzhy8',
    'container.build_id' => 'fe20ac58',
    'container.build_time' => 1574086819,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBqfzhy8');
