<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'BnvWebLogger' shared service.

$this->services['BnvWebLogger'] = $instance = new \Symfony\Bridge\Monolog\Logger('BnvWeb');

$instance->pushProcessor(${($_ = isset($this->services['BnvWebUserLoggerProcessor']) ? $this->services['BnvWebUserLoggerProcessor'] : $this->load('getBnvWebUserLoggerProcessorService.php')) && false ?: '_'});
$instance->pushHandler(${($_ = isset($this->services['StreamHandler']) ? $this->services['StreamHandler'] : $this->load('getStreamHandlerService.php')) && false ?: '_'});
$instance->pushHandler(${($_ = isset($this->services['BnvLoggerHandler']) ? $this->services['BnvLoggerHandler'] : $this->load('getBnvLoggerHandlerService.php')) && false ?: '_'});

return $instance;
