<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'BnvLoggerHandler' shared service.

include_once $this->targetDirs[3].'/src/Binovo/ElkarBackupBundle/Logger/LoggerHandler.php';

$this->services['BnvLoggerHandler'] = $instance = new \Binovo\ElkarBackupBundle\Logger\LoggerHandler();

$instance->setContainer($this);

return $instance;
