<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'BnvWebUserLoggerProcessor' shared service.

include_once $this->targetDirs[3].'/vendor/monolog/monolog/src/Monolog/Processor/WebProcessor.php';
include_once $this->targetDirs[3].'/src/Binovo/ElkarBackupBundle/Logger/WebUserLoggerProcessor.php';

$this->services['BnvWebUserLoggerProcessor'] = $instance = new \Binovo\ElkarBackupBundle\Logger\WebUserLoggerProcessor();

$instance->setContainer($this);

return $instance;
