<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.expressions.compiler' shared service.

include_once $this->targetDirs[3].'/vendor/jms/security-extra-bundle/Security/Authorization/Expression/ExpressionCompiler.php';
include_once $this->targetDirs[3].'/vendor/jms/security-extra-bundle/Security/Authorization/Expression/Compiler/Func/FunctionCompilerInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/security-extra-bundle/Security/Acl/Expression/HasPermissionFunctionCompiler.php';
include_once $this->targetDirs[3].'/vendor/jms/security-extra-bundle/Security/Acl/Expression/HasClassPermissionFunctionCompiler.php';
include_once $this->targetDirs[3].'/vendor/jms/security-extra-bundle/Security/Authorization/Expression/Compiler/TypeCompilerInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/security-extra-bundle/Security/Authorization/Expression/Compiler/ParameterExpressionCompiler.php';
include_once $this->targetDirs[3].'/vendor/jms/security-extra-bundle/Security/Authorization/Expression/Compiler/VariableExpressionCompiler.php';
include_once $this->targetDirs[3].'/vendor/jms/security-extra-bundle/Security/Authorization/Expression/Compiler/ContainerAwareVariableCompiler.php';

$this->services['security.expressions.compiler'] = $instance = new \JMS\SecurityExtraBundle\Security\Authorization\Expression\ExpressionCompiler();

$a = new \JMS\SecurityExtraBundle\Security\Authorization\Expression\Compiler\ContainerAwareVariableCompiler();
$a->setMaps(['trust_resolver' => 'security.authentication.trust_resolver', 'role_hierarchy' => 'security.role_hierarchy', 'permission_evaluator' => 'security.acl.permission_evaluator', 'token_storage' => 'security.token_storage', 'authorization_checker' => 'security.authorization_checker'], []);

$instance->addFunctionCompiler(new \JMS\SecurityExtraBundle\Security\Acl\Expression\HasPermissionFunctionCompiler());
$instance->addFunctionCompiler(new \JMS\SecurityExtraBundle\Security\Acl\Expression\HasClassPermissionFunctionCompiler());
$instance->addTypeCompiler(new \JMS\SecurityExtraBundle\Security\Authorization\Expression\Compiler\ParameterExpressionCompiler());
$instance->addTypeCompiler($a);

return $instance;
