<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.expressions.handler' shared service.

include_once $this->targetDirs[3].'/vendor/jms/security-extra-bundle/Security/Authorization/Expression/ExpressionHandlerInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/security-extra-bundle/Security/Authorization/Expression/ContainerAwareExpressionHandler.php';

return $this->services['security.expressions.handler'] = new \JMS\SecurityExtraBundle\Security\Authorization\Expression\ContainerAwareExpressionHandler($this);
