<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'StreamHandler' shared service.

$this->services['StreamHandler'] = $instance = new \Monolog\Handler\StreamHandler(($this->targetDirs[2].'/logs/BnvLog.log'), 200);

$instance->setFormatter(${($_ = isset($this->services['BnvWebLoggerFormatter']) ? $this->services['BnvWebLoggerFormatter'] : $this->load('getBnvWebLoggerFormatterService.php')) && false ?: '_'});

return $instance;
