<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access.pointcut' shared service.

include_once $this->targetDirs[3].'/vendor/jms/aop-bundle/Aop/PointcutInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/security-extra-bundle/Security/Authorization/Interception/SecurityPointcut.php';

$this->services['security.access.pointcut'] = $instance = new \JMS\SecurityExtraBundle\Security\Authorization\Interception\SecurityPointcut(${($_ = isset($this->services['security.extra.metadata_factory']) ? $this->services['security.extra.metadata_factory'] : $this->load('getSecurity_Extra_MetadataFactoryService.php')) && false ?: '_'}, false, []);

$instance->setSecuredClasses([]);

return $instance;
