<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'LoginListener' shared service.

include_once $this->targetDirs[3].'/src/Binovo/ElkarBackupBundle/Listener/LoginListener.php';

return $this->services['LoginListener'] = new \Binovo\ElkarBackupBundle\Listener\LoginListener($this);
