<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.expressions.reverse_interpreter' shared service.

include_once $this->targetDirs[3].'/vendor/jms/security-extra-bundle/Security/Authorization/Expression/ReverseInterpreter.php';
include_once $this->targetDirs[3].'/vendor/jms/security-extra-bundle/Security/Authorization/Expression/ExpressionHandlerInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/security-extra-bundle/Security/Authorization/Expression/ContainerAwareExpressionHandler.php';

return $this->services['security.expressions.reverse_interpreter'] = new \JMS\SecurityExtraBundle\Security\Authorization\Expression\ReverseInterpreter(${($_ = isset($this->services['security.expressions.compiler']) ? $this->services['security.expressions.compiler'] : $this->load('getSecurity_Expressions_CompilerService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.expressions.handler']) ? $this->services['security.expressions.handler'] : ($this->services['security.expressions.handler'] = new \JMS\SecurityExtraBundle\Security\Authorization\Expression\ContainerAwareExpressionHandler($this))) && false ?: '_'});
