<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Tahoe' shared service.

include_once $this->targetDirs[3].'/src/Binovo/ElkarTahoeBundle/Utils/TahoeBackup.php';

return $this->services['Tahoe'] = new \Binovo\ElkarTahoeBundle\Utils\TahoeBackup(${($_ = isset($this->services['BnvWebLogger']) ? $this->services['BnvWebLogger'] : $this->load('getBnvWebLoggerService.php')) && false ?: '_'}, '/var/lib/elkarbackup');
