<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'uri_signer' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/UriSigner.php';

return $this->services['uri_signer'] = new \Symfony\Component\HttpKernel\UriSigner('fba546d6ab6abc4a01391d161772a14e093c7aa2');
